name: Backport to older releases
on:
  push:
    branches:
    - master

jobs:

  backport:
    strategy:
      fail-fast: false
      matrix:
        branch: [ 'release-0.28', 'release-0.27' ]
    name: Backport change to branch ${{ matrix.branch }}

    runs-on: ubuntu-20.04

    steps:
    - name: Check out code
      uses: actions/checkout@v1
      with:
        fetch-depth: 0
    - name: Create a cherry-pick PR
      run: |
        if ! git diff --quiet HEAD^ HEAD -- vendor/libgit2; then
          echo '::warning::Skipping cherry-pick since it is a vendored libgit2 bump'
          exit 0
        fi

        git checkout ${{ matrix.branch }}
        git switch -c "cherry-pick-${{ github.id }}-${{ matrix.branch }}"
        git cherry-pick -x ${{ github.sha }}
        gh pr create \
          --base ${{ matrix.branch }} \
          --title "$(git show --format="%s" --no-patch HEAD)" \
          --body "$(git show --format="%b" --no-patch HEAD)"
